image: registry.gitlab.com/pages/hugo/hugo_extended:0.139.3

stages:
  - deploy

pages:
  stage: deploy
  script:
    - apk add --no-cache bash wget iputils tar
    - ./install-revealjs
    - hugo -b "https://danielk.developer.irf.se/phd-course-software-development"
  artifacts:
    expire_in: 5 minutes
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
