image: alpine:3.18.0

default:
  tags:
    - internal

pages:
  script:
    - apk add --no-cache bash wget iputils tar go hugo
    - ./install-revealjs
    - mkdir -p public
    - ./fix-hash
    - cp -rv presentations static media dist plugin css js index.html public/

  artifacts:
    paths:
      - public
