baseURL = 'https://danielk.developer.irf.se/phd-course-software-development'
description = "Pages and content for PhD level course named 'Software development for researchers'"
contentdir = "content"
layoutdir = "layouts"
assetDir = "assets"
publishdir = "public"
themesDir = "themes"
languageCode = "en-GB"

defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 50

theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
[[menu.after]]
  name = "IRF Gitlab"
  url = "https://gitlab.irf.se/danielk/phd-course-software-development#"
  weight = 10


[params]
  BookTheme = 'auto'
  BookToC = true
  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection = 'docs'
  BookRepo = 'https://gitlab.irf.se/danielk/phd-course-software-development'

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = '2025-01-17'
  BookSearch = true

  BookComments = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
  # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
  # Theme will print warning if page referenced in markdown does not exists.
  BookPortableLinks = true

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
  BookServiceWorker = true
