kanban
  [Todo]
    [Update to numpy 2.x]@{priority: 'High'}
    [Fix edge case in coordinate transform]@{priority: 'Low'}
  [In progress]
    [Fix faulty background subtraction when no TX signal]@{priority: 'Very High', assigned: 'Daniel'}
    [Support macOS]@{priority: 'High', assigned: 'Hampus'}
    [Update plotting CLI with requested args]@{priority: 'Very Low', assigned: 'Daniel'}
  [Code review]
    [Support new radar experiment v2.1]@{priority: 'Very High', assigned: 'Ingar'}
  [Done]
    [Fix colorbar bug in raw data plotting]@{priority: 'Very Low'}
