flowchart TD
    style A fill:#314f73
    style B fill:#314f73
    style C fill:#314f73
    style T1 fill:#496135
    style T2 fill:#496135
    style T3 fill:#496135
    style f1 fill:#5c3c32
    style f2 fill:#5c3c32
    style f3 fill:#5c3c32
    A[Third commit
    Modify README.md
    87fg9d]@{color=red} --> B[Second commit
    Create data.csv
    9fsdf9]
    B --> C[First commit
    Create README.md
    s9d8fd]
    A --> T1(Tree
    98384s)
    B --> T2(Tree
    3llkdj)
    C --> T3(Tree
    o7ue83)
    T3 --> f1(README.md blob
    js8sd7)
    T2 --> f1(README.md blob
    js8sd7)
    T2 --> f2(data.csv blob
    mcv7y8)
    T1 --> f2(data.csv blob
    mcv7y8)
    T1 --> f3(README.md v2 blob
    js8sd7)
